#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef NUANCEMESSAGINGUI_SWIFT_H
#define NUANCEMESSAGINGUI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="NuanceMessagingUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
typedef SWIFT_ENUM(NSInteger, CallButtonPosition, open) {
  CallButtonPositionMicroPhone = 0,
  CallButtonPositionCall = 1,
  CallButtonPositionSpeaker = 2,
  CallButtonPositionNone = -10,
};

@class CallToChatPropertieClass;
@class UIColor;
@class NSData;
@class NSString;
@class UIFont;
@class UIImage;
enum TitlePosition : NSInteger;

SWIFT_CLASS("_TtC17NuanceMessagingUI21CallSupportProperties")
@interface CallSupportProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) CallToChatPropertieClass * _Nonnull callToChatSwitcherProperties;
@property (nonatomic, strong) UIColor * _Nonnull microphoneDeniedScreenTitleBarColor;
@property (nonatomic, strong) UIColor * _Nonnull callExitScreenTitleBarColor;
@property (nonatomic, strong) UIColor * _Nonnull callFailedScreenTitleBarColor;
@property (nonatomic) NSInteger callButtonsHeight;
@property (nonatomic, strong) NSData * _Nullable ringerSoundData;
@property (nonatomic) NSInteger callButtonsSeperatorHeight;
@property (nonatomic) NSInteger callButtonsSeperatorCornerRadius;
@property (nonatomic) NSInteger callButtonsSeperatorBorderWidth;
@property (nonatomic, strong) UIColor * _Nonnull callButtonsSeperatorBorderColor;
@property (nonatomic) NSInteger callButtonsSeperatorLeftMargin;
@property (nonatomic) NSInteger callButtonsSeperatorRightMargin;
@property (nonatomic) NSInteger callButtonsSeperatorBottomMargin;
@property (nonatomic, strong) UIColor * _Nonnull callButtonsSeperatorColor;
@property (nonatomic) NSInteger detachCallerIconHeight;
@property (nonatomic) NSInteger detachCallerIconCornerRadius;
@property (nonatomic) NSInteger detachCallerIconBorderWidth;
@property (nonatomic, strong) UIColor * _Nonnull detachCallerIconBorderColor;
@property (nonatomic) BOOL detachCallerIcon;
@property (nonatomic, copy) NSString * _Nonnull callerIconHungTitle;
@property (nonatomic, copy) NSString * _Nonnull callerIconDialTitle;
@property (nonatomic, copy) NSData * _Nullable callerDialIconData;
@property (nonatomic, copy) NSData * _Nullable callerHungIconData;
@property (nonatomic) NSInteger callerIconTopMargin;
@property (nonatomic) NSInteger callerIconLeftMargin;
@property (nonatomic) NSInteger callerIconRightMargin;
@property (nonatomic) NSInteger callerLabelBottomMargin;
@property (nonatomic, strong) UIColor * _Nonnull callerIconTextColor;
@property (nonatomic, strong) UIColor * _Nonnull callerIconBackgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull callerIconTextFontStyle;
@property (nonatomic, copy) NSString * _Nonnull microphoneIconMuteTitle;
@property (nonatomic, copy) NSString * _Nonnull microphoneIconUnMuteTitle;
@property (nonatomic, copy) NSData * _Nullable microphoneUnmuteIconData;
@property (nonatomic, copy) NSData * _Nullable microphoneMuteIconData;
@property (nonatomic) NSInteger microphoneIconTopMargin;
@property (nonatomic) NSInteger microphoneIconRightMargin;
@property (nonatomic) NSInteger microphoneIconLeftMargin;
@property (nonatomic) NSInteger microphoneLabelBottomMargin;
@property (nonatomic, strong) UIColor * _Nonnull microphoneIconTextColor;
@property (nonatomic, strong) UIColor * _Nonnull microphoneIconBackgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull microphoneIconTextFontStyle;
@property (nonatomic, copy) NSString * _Nonnull speakerOnTitle;
@property (nonatomic, copy) NSString * _Nonnull speakerOffTitle;
@property (nonatomic, copy) NSData * _Nullable speakerOffData;
@property (nonatomic, copy) NSData * _Nullable speakerOnData;
@property (nonatomic) NSInteger speakerIconTopMargin;
@property (nonatomic) NSInteger speakerIconRightMargin;
@property (nonatomic) NSInteger speakerIconLeftMargin;
@property (nonatomic) NSInteger speakerLabelBottomMargin;
@property (nonatomic, strong) UIColor * _Nonnull speakerIconTextColor;
@property (nonatomic, strong) UIColor * _Nonnull speakerIconBackgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull speakerIconTextFontStyle;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull callButtonsPosition;
@property (nonatomic, strong) UIColor * _Nonnull callButtonsContainerBackgroundColor;
@property (nonatomic) NSInteger callButtonsContainerViewHeight;
@property (nonatomic) NSInteger callButtonsContainerCornerRadius;
@property (nonatomic) NSInteger callButtonsContainerBorderWidth;
@property (nonatomic, strong) UIColor * _Nonnull callButtonsContainerBorderColor;
@property (nonatomic) NSInteger callButtonsContainerRightMargin;
@property (nonatomic) NSInteger callButtonsContainerLeftMargin;
@property (nonatomic) NSInteger callButtonsContainerBottomMargin;
@property (nonatomic, copy) NSString * _Nonnull connectingDisclaimerText;
@property (nonatomic, strong) UIColor * _Nonnull connectingDisclaimerBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull connectingDisclaimerColor;
@property (nonatomic) NSTextAlignment connectingDisclaimerTextAllignMent;
@property (nonatomic, strong) UIFont * _Nonnull connectingDisclaimerFontStyle;
@property (nonatomic) NSInteger connectingDisclaimerTextBottomMargin;
@property (nonatomic) NSInteger connectingDisclaimerTextLeftMargin;
@property (nonatomic) NSInteger connectingDisclaimerTextRightMargin;
@property (nonatomic, copy) NSString * _Nonnull callConnectingText;
@property (nonatomic, copy) NSString * _Nonnull callDisconnectedText;
@property (nonatomic, copy) NSString * _Nonnull callDisconnectingText;
@property (nonatomic, copy) NSString * _Nonnull callFailedText;
@property (nonatomic, copy) NSString * _Nonnull callConnectedText;
@property (nonatomic, copy) NSString * _Nonnull callStatusText;
@property (nonatomic, strong) UIColor * _Nonnull callStatusBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull callStatusColor;
@property (nonatomic) NSTextAlignment callStatusTextAllignMent;
@property (nonatomic, strong) UIFont * _Nonnull callStatusFontStyle;
@property (nonatomic) NSInteger callStatusTextTopMargin;
@property (nonatomic) NSInteger callStatusTextLeftMargin;
@property (nonatomic) NSInteger callStatusTextRightMargin;
@property (nonatomic) NSInteger callButtonSeperatorViewCornerRadius;
@property (nonatomic) NSInteger callButtonSeperatorViewBorderWidth;
@property (nonatomic, strong) UIColor * _Nonnull callButtonSeperatorViewBorderColor;
@property (nonatomic) NSInteger callButtonSeperatorViewWidth;
@property (nonatomic) NSInteger callButtonSeperatorTopMargin;
@property (nonatomic) NSInteger callButtonSeperatorBottomMargin;
@property (nonatomic, copy) NSData * _Nullable callConnectedImage;
@property (nonatomic) NSInteger callConnectedImageTopMargin;
@property (nonatomic) NSInteger callConnectedImageLeftMargin;
@property (nonatomic) NSInteger callConnectedImageRightMargin;
@property (nonatomic) NSInteger callConnectedImageHeight;
@property (nonatomic, strong) UIColor * _Nonnull callConnectedImageBackgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull callConnectedTextFontStyle;
@property (nonatomic, strong) UIColor * _Nonnull callConnectedTextBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull callConnectedTextColor;
@property (nonatomic) NSTextAlignment callConnectedTextAllignMent;
@property (nonatomic) NSInteger connectingImageLeftMargin;
@property (nonatomic) NSInteger connectingImageTopMargin;
@property (nonatomic) NSInteger connectingImageWidth;
@property (nonatomic) NSInteger connectingImageHeight;
@property (nonatomic, strong) UIImage * _Nullable connectingImageAnimatedImageData;
@property (nonatomic, strong) UIColor * _Nonnull connectingImageBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull callScreenTitleTextColor;
@property (nonatomic, strong) UIColor * _Nonnull callScreenTitleBarColor;
@property (nonatomic) BOOL hideBackButton;
@property (nonatomic, copy) NSString * _Nonnull callScreenTitleText;
@property (nonatomic, strong) UIFont * _Nonnull callScreenTitleFontStyle;
@property (nonatomic, strong) UIColor * _Nonnull callScreenBackgroundColor;
@property (nonatomic, copy) NSData * _Nullable logoImageData;
@property (nonatomic) NSInteger logoImageWidth;
@property (nonatomic) NSInteger logoImageHeight;
@property (nonatomic, copy) NSString * _Nonnull titleBarCloseButtonTextName;
@property (nonatomic, strong) UIColor * _Nonnull titleBarCloseButtonTextColor;
@property (nonatomic, copy) NSString * _Nonnull titleBarCloseButtonAccessibilityMessage;
@property (nonatomic, copy) NSData * _Nullable titleBarCloseButtonImageData;
@property (nonatomic) NSInteger titleBarCloseButtonWidth;
@property (nonatomic) NSInteger titleBarCloseButtonHeight;
@property (nonatomic) enum TitlePosition callScreenTitlePosition;
@property (nonatomic, copy) NSString * _Nonnull titleBarMinimizeButtonTextName;
@property (nonatomic, strong) UIColor * _Nonnull titleBarMinimizeButtonTextColor;
@property (nonatomic, copy) NSString * _Nonnull titleBarMinimizeButtonAccessibilityMessage;
@property (nonatomic, copy) NSData * _Nullable titleBarMinimizeButtonImageData;
@property (nonatomic) NSInteger titleBarMinimizeButtonWidth;
@property (nonatomic) NSInteger titleBarMinimizeButtonHeight;
@property (nonatomic, copy) NSData * _Nullable microphoneDeniedScreenImage;
@property (nonatomic) NSInteger microphoneDeniedScreenImageHeight;
@property (nonatomic) NSInteger microphoneDeniedScreenImageTopMargin;
@property (nonatomic) NSInteger microphoneDeniedScreenImageLeftMargin;
@property (nonatomic) NSInteger microphoneDeniedScreenImageRightMargin;
@property (nonatomic, copy) NSString * _Nonnull microphoneDeniedScreenStatusText;
@property (nonatomic, strong) UIColor * _Nonnull microphoneDeniedScreenStatusBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull microphoneDeniedScreenStatusColor;
@property (nonatomic) NSTextAlignment microphoneDeniedScreenStatusTextAllignMent;
@property (nonatomic, strong) UIFont * _Nonnull microphoneDeniedScreenStatusFontStyle;
@property (nonatomic) NSInteger microphoneDeniedScreenStatusBottomMargin;
@property (nonatomic) NSInteger microphoneDeniedScreenStatusLeftMargin;
@property (nonatomic) NSInteger microphoneDeniedScreenStatusRightMargin;
@property (nonatomic, copy) NSData * _Nullable callExitScreenImage;
@property (nonatomic) NSInteger callExitScreenImageHeight;
@property (nonatomic) NSInteger callExitScreenImageTopMargin;
@property (nonatomic) NSInteger callExitScreenImageLeftMargin;
@property (nonatomic) NSInteger callExitScreenImageRightMargin;
@property (nonatomic, copy) NSString * _Nonnull callExitScreenAgentNotAvailable;
@property (nonatomic, copy) NSString * _Nonnull callExitScreenSuccess;
@property (nonatomic, copy) NSString * _Nonnull callExitScreenFailed;
@property (nonatomic, strong) UIColor * _Nonnull callExitScreenStatusBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull callExitScreenStatusColor;
@property (nonatomic) NSTextAlignment callExitScreenStatusTextAllignMent;
@property (nonatomic, strong) UIFont * _Nonnull callExitScreenStatusFontStyle;
@property (nonatomic) NSInteger callExitScreenStatusBottomMargin;
@property (nonatomic) NSInteger callExitScreenStatusLeftMargin;
@property (nonatomic) NSInteger callExitScreenStatusRightMargin;
@property (nonatomic, copy) NSData * _Nullable callFailedScreenImage;
@property (nonatomic) NSInteger callFailedScreenImageHeight;
@property (nonatomic) NSInteger callFailedScreenImageTopMargin;
@property (nonatomic) NSInteger callFailedScreenImageLeftMargin;
@property (nonatomic) NSInteger callFailedScreenImageRightMargin;
@property (nonatomic, strong) UIColor * _Nonnull callFailedScreenStatusBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull callFailedStatusColor;
@property (nonatomic) NSTextAlignment callFailedScreenStatusTextAllignMent;
@property (nonatomic, strong) UIFont * _Nonnull callFailedScreenStatusFontStyle;
@property (nonatomic) NSInteger callFailedScreenStatusBottomMargin;
@property (nonatomic) NSInteger callFailedScreenStatusLeftMargin;
@property (nonatomic) NSInteger callFailedScreenStatusRightMargin;
@property (nonatomic, copy) NSData * _Nullable chatButtonImageData;
@property (nonatomic, strong) UIColor * _Nonnull chatButtonBorderColor;
@property (nonatomic) NSInteger chatButtonBorderWidth;
@property (nonatomic) NSInteger chatButtonCornerRadius;
@property (nonatomic, copy) NSString * _Nonnull chatButtonTitle;
@property (nonatomic, strong) UIColor * _Nonnull chatButtonBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull chatButtonTextColor;
@property (nonatomic) NSInteger chatButtonBottomMargin;
@property (nonatomic) NSInteger chatButtonLeftMargin;
@property (nonatomic) NSInteger chatButtonRightMargin;
@property (nonatomic, copy) NSData * _Nullable bottomCloseButtonImageData;
@property (nonatomic, strong) UIColor * _Nonnull bottomCloseButtonBorderColor;
@property (nonatomic) NSInteger bottomCloseButtonBorderWidth;
@property (nonatomic) NSInteger bottomCloseButtonCornerRadius;
@property (nonatomic, copy) NSString * _Nonnull bottomCloseButtonTitle;
@property (nonatomic, strong) UIColor * _Nonnull bottomCloseButtonBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull bottomCloseButtonTextColor;
@property (nonatomic) NSInteger bottomCloseBottomMargin;
@property (nonatomic) NSInteger bottomCloseLeftMargin;
@property (nonatomic) NSInteger bottomCloseRightMargin;
@property (nonatomic, copy) NSString * _Nonnull host;
@property (nonatomic, copy) NSString * _Nonnull authCredID;
@property (nonatomic, copy) NSString * _Nonnull nuanceCallInitialText;
@end


SWIFT_CLASS("_TtC17NuanceMessagingUI24CallToChatPropertieClass")
@interface CallToChatPropertieClass : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull titleBarColor;
@property (nonatomic, copy) NSString * _Nonnull infoLabelText;
@property (nonatomic) NSInteger infoLabelTopMargin;
@property (nonatomic) NSInteger infoLabelLeftMargin;
@property (nonatomic) NSInteger infoLabelRightMargin;
@property (nonatomic, strong) UIColor * _Nonnull infoLabelTextColor;
@property (nonatomic, strong) UIColor * _Nonnull infoLabelBackgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull infoLabelFontStyle;
@property (nonatomic) NSInteger centerImageTopMargin;
@property (nonatomic) NSInteger centerImageLeftMargin;
@property (nonatomic) NSInteger centerImageRightMargin;
@property (nonatomic) NSInteger centerImageHeight;
@property (nonatomic, strong) UIColor * _Nonnull centerImageBackgroundColor;
@property (nonatomic, copy) NSData * _Nullable centerImageData;
@property (nonatomic) NSInteger horizontalSeperatorHeight;
@property (nonatomic) NSInteger horizontalSeperatorCornerRadius;
@property (nonatomic) NSInteger horizontalSeperatorBorderWidth;
@property (nonatomic, strong) UIColor * _Nonnull horizontalSeperatorBorderColor;
@property (nonatomic) NSInteger horizontalSeperatorLeftMargin;
@property (nonatomic) NSInteger horizontalSeperatorRightMargin;
@property (nonatomic, strong) UIColor * _Nonnull horizontalSeperatorColor;
@property (nonatomic) NSInteger horizontalSeperatorBottomMargin;
@property (nonatomic, copy) NSString * _Nonnull connectButtonTitle;
@property (nonatomic) NSInteger connectButtonBottomMargin;
@property (nonatomic) NSInteger connectButtonRightMargin;
@property (nonatomic) NSInteger connectButtonLeftMargin;
@property (nonatomic) NSInteger connectButtonHeight;
@property (nonatomic, strong) UIColor * _Nonnull connectButtonTextColor;
@property (nonatomic, strong) UIColor * _Nonnull connectButtonBackgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull connectButtonTextFontStyle;
@property (nonatomic, copy) NSData * _Nullable connectButtonbackgroundImage;
@property (nonatomic, copy) NSString * _Nonnull returnButtonTitle;
@property (nonatomic) NSInteger returnButtonBottomMargin;
@property (nonatomic) NSInteger returnButtonRightMargin;
@property (nonatomic) NSInteger returnButtonLeftMargin;
@property (nonatomic) NSInteger returnButtonHeight;
@property (nonatomic, strong) UIColor * _Nonnull returnButtonTextColor;
@property (nonatomic, strong) UIColor * _Nonnull returnButtonBackgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull returnButtonTextFontStyle;
@property (nonatomic, copy) NSData * _Nullable returnButtonbackgroundImage;
@end


SWIFT_CLASS("_TtC17NuanceMessagingUI20ChatHeaderProperties")
@interface ChatHeaderProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) BOOL showDisclaimerHeader;
@property (nonatomic) BOOL autoHideDisclaimerHeader;
@property (nonatomic) NSInteger autoHideHeaderTime;
@property (nonatomic, copy) NSString * _Nonnull disclaimerText;
@property (nonatomic, strong) UIColor * _Nonnull disclaimerTextColor;
@property (nonatomic, strong) UIFont * _Nonnull disclaimerTextFontStyle;
@property (nonatomic) NSTextAlignment disclaimerTextAlignment;
@end


SWIFT_CLASS("_TtC17NuanceMessagingUI24ChatToCallPropertieClass")
@interface ChatToCallPropertieClass : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull titleBarColor;
@property (nonatomic, copy) NSString * _Nonnull infoLabelText;
@property (nonatomic) NSInteger infoLabelTopMargin;
@property (nonatomic) NSInteger infoLabelLeftMargin;
@property (nonatomic) NSInteger infoLabelRightMargin;
@property (nonatomic, strong) UIColor * _Nonnull infoLabelTextColor;
@property (nonatomic, strong) UIColor * _Nonnull infoLabelBackgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull infoLabelFontStyle;
@property (nonatomic) NSInteger centerImageTopMargin;
@property (nonatomic) NSInteger centerImageLeftMargin;
@property (nonatomic) NSInteger centerImageRightMargin;
@property (nonatomic) NSInteger centerImageHeight;
@property (nonatomic, strong) UIColor * _Nonnull centerImageBackgroundColor;
@property (nonatomic, copy) NSData * _Nullable centerImageData;
@property (nonatomic) NSInteger horizontalSeperatorHeight;
@property (nonatomic) NSInteger horizontalSeperatorCornerRadius;
@property (nonatomic) NSInteger horizontalSeperatorBorderWidth;
@property (nonatomic, strong) UIColor * _Nonnull horizontalSeperatorBorderColor;
@property (nonatomic) NSInteger horizontalSeperatorLeftMargin;
@property (nonatomic) NSInteger horizontalSeperatorRightMargin;
@property (nonatomic, strong) UIColor * _Nonnull horizontalSeperatorColor;
@property (nonatomic) NSInteger horizontalSeperatorBottomMargin;
@property (nonatomic, copy) NSString * _Nonnull connectButtonTitle;
@property (nonatomic) NSInteger connectButtonBottomMargin;
@property (nonatomic) NSInteger connectButtonRightMargin;
@property (nonatomic) NSInteger connectButtonLeftMargin;
@property (nonatomic) NSInteger connectButtonHeight;
@property (nonatomic, strong) UIColor * _Nonnull connectButtonTextColor;
@property (nonatomic, strong) UIColor * _Nonnull connectButtonBackgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull connectButtonTextFontStyle;
@property (nonatomic, copy) NSData * _Nullable connectButtonbackgroundImage;
@property (nonatomic, copy) NSString * _Nonnull returnButtonTitle;
@property (nonatomic) NSInteger returnButtonBottomMargin;
@property (nonatomic) NSInteger returnButtonRightMargin;
@property (nonatomic) NSInteger returnButtonLeftMargin;
@property (nonatomic) NSInteger returnButtonHeight;
@property (nonatomic, strong) UIColor * _Nonnull returnButtonTextColor;
@property (nonatomic, strong) UIColor * _Nonnull returnButtonBackgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull returnButtonTextFontStyle;
@property (nonatomic, copy) NSData * _Nullable returnButtonbackgroundImage;
@end


SWIFT_CLASS("_TtC17NuanceMessagingUI27CustomerInformationMessages")
@interface CustomerInformationMessages : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Nonnull messagingNotAvailable;
@property (nonatomic, copy) NSString * _Nonnull serviceQueued;
@property (nonatomic, copy) NSString * _Nonnull agentNowAvailable;
@property (nonatomic, copy) NSString * _Nonnull networkNotAvaliable;
@property (nonatomic, copy) NSString * _Nonnull networkAvailable;
@property (nonatomic, copy) NSString * _Nonnull agentLeftConversation;
@property (nonatomic, copy) NSString * _Nonnull agentResolvedConversation;
@property (nonatomic, copy) NSString * _Nonnull agentTimedOut;
@property (nonatomic, copy) NSString * _Nonnull connectionLost;
@property (nonatomic, copy) NSString * _Nonnull serviceDenied;
@property (nonatomic, copy) NSString * _Nonnull defaultCustomerName;
@property (nonatomic, copy) NSString * _Nonnull closeButtonAccessibilityMessage;
@property (nonatomic, copy) NSString * _Nonnull minimizeButtonAccessibilityMessage;
@property (nonatomic, copy) NSString * _Nonnull emailButtonAccessibilityMessage;
@property (nonatomic, copy) NSString * _Nonnull shareButtonAccessibilityMessage;
@property (nonatomic, copy) NSString * _Nonnull option1ButtonAccessibilityMessage;
@property (nonatomic, copy) NSString * _Nonnull option2ButtonAccessibilityMessage;
@property (nonatomic, copy) NSString * _Nonnull chimeButtonOnAccessibilityMessage;
@property (nonatomic, copy) NSString * _Nonnull chimeButtonOffAccessibilityMessage;
@property (nonatomic, copy) NSString * _Nonnull sendButtonAccessibilityMessage;
@property (nonatomic, copy) NSString * _Nonnull startRecordingAccessibilityMessage;
@property (nonatomic, copy) NSString * _Nonnull stopRecordingAccessibilityMessage;
@property (nonatomic, copy) NSString * _Nonnull InputTextAccessibilityMessage;
@property (nonatomic, copy) NSString * _Nonnull customerSurveyAlertTitle;
@property (nonatomic, copy) NSString * _Nonnull customerSurveyAlertMessage;
@property (nonatomic, copy) NSString * _Nonnull customerSurveyAlertOKText;
@property (nonatomic, copy) NSString * _Nonnull customerSurveyAlertCancelText;
@property (nonatomic, copy) NSString * _Nonnull titleAccessibilityMessage;
@property (nonatomic, copy) NSString * _Nonnull agentTransfer;
@property (nonatomic, copy) NSString * _Nonnull agentTransferConnected;
@property (nonatomic, copy) NSString * _Nonnull agentLost;
@property (nonatomic, copy) NSString * _Nonnull appBackgroundInfoMsg;
@property (nonatomic, copy) NSString * _Nonnull appBackgroundType;
@end


SWIFT_CLASS("_TtC17NuanceMessagingUI28CustomerInputFieldProperties")
@interface CustomerInputFieldProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Nonnull hintText;
@property (nonatomic, strong) UIColor * _Nonnull borderColor;
@property (nonatomic) NSInteger borderWidth;
@property (nonatomic) NSInteger cornerRadius;
@property (nonatomic, strong) UIColor * _Nonnull inputMessageBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull textColor;
@property (nonatomic, strong) UIColor * _Nonnull placeHolderColor;
@property (nonatomic, strong) UIColor * _Nonnull containerBackgroundColor;
@property (nonatomic) BOOL dismissKeyBoardOnReturn;
@property (nonatomic) BOOL sendMsgOnReturn;
@property (nonatomic, strong) UIFont * _Nonnull textFieldFont;
@property (nonatomic) NSInteger inputFieldLeftMargin;
@property (nonatomic) NSInteger inputFieldRightMargin;
@property (nonatomic) NSInteger inputFieldTopMargin;
@property (nonatomic) NSInteger inputFieldBottomMargin;
@property (nonatomic) NSInteger textFieldTopPadding;
@property (nonatomic) NSInteger textFieldBottomPadding;
@property (nonatomic) NSInteger textFieldLeftPadding;
@property (nonatomic) NSInteger textFieldRightPadding;
@property (nonatomic) UIKeyboardType keyboardType;
@property (nonatomic) BOOL isDynamicSizeTextFieldRequired;
@property (nonatomic) NSInteger maxLines;
@property (nonatomic) BOOL isCharacterLimitRequired;
@property (nonatomic) BOOL limitInputChars;
@property (nonatomic) NSInteger limitDisplayThreshold;
@property (nonatomic) NSInteger characterLimitForVA;
@property (nonatomic) NSInteger characterLimitBottomPadding;
@property (nonatomic) NSInteger characterLimitRightPadding;
@property (nonatomic) NSInteger characterLimitTopPadding;
@property (nonatomic) NSInteger characterLimitViewWidth;
@property (nonatomic, strong) UIColor * _Nonnull characterLimitTextColor;
@property (nonatomic, strong) UIFont * _Nonnull characterLimitTextFont;
@property (nonatomic) NSTextAlignment inputTextAlignment;
@property (nonatomic) BOOL showSendToolBarButtonInKeyboard;
@end


SWIFT_CLASS("_TtC17NuanceMessagingUI19EmailViewProperties")
@interface EmailViewProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull placeholderPadding;
@property (nonatomic) float transperentBackgroundColorOpacity;
@property (nonatomic, strong) UIColor * _Nonnull transperentBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic) double emailPopupHeight;
@property (nonatomic) double emailPopupHeightAtLandscape;
@property (nonatomic, copy) NSString * _Nonnull titleBarText;
@property (nonatomic, strong) UIColor * _Nonnull titleBarTextColor;
@property (nonatomic, strong) UIFont * _Nonnull titleBarTextFontStyle;
@property (nonatomic) NSTextAlignment titleBarTextAllignment;
@property (nonatomic, copy) NSString * _Nonnull descriptionText;
@property (nonatomic, strong) UIColor * _Nonnull descriptionTextColor;
@property (nonatomic, strong) UIFont * _Nonnull descriptionTextFontStyle;
@property (nonatomic) NSTextAlignment descriptionTextAllignment;
@property (nonatomic, copy) NSString * _Nonnull cancelButtonText;
@property (nonatomic, strong) UIColor * _Nonnull cancelButtonBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull cancelButtonBackgroundViewColor;
@property (nonatomic, strong) UIColor * _Nonnull cancelButtonTextColor;
@property (nonatomic, strong) UIFont * _Nonnull cancelButtonFontStyle;
@property (nonatomic) NSInteger buttonsViewHeight;
@property (nonatomic) NSInteger buttonInBetweenBorderWidth;
@property (nonatomic) NSInteger buttonViewTopBorderWidth;
@property (nonatomic, strong) UIColor * _Nonnull buttonBorderColor;
@property (nonatomic, strong) UIColor * _Nonnull sendButtonTextColor;
@property (nonatomic, copy) NSString * _Nonnull sendButtonText;
@property (nonatomic, strong) UIColor * _Nonnull sendButtonBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull sendButtonBackgroundViewColor;
@property (nonatomic, strong) UIFont * _Nonnull sendButtonFontStyle;
@property (nonatomic) NSInteger emailTextFieldCornerRadius;
@property (nonatomic) NSInteger emailTextFieldBorderWidth;
@property (nonatomic, strong) UIColor * _Nonnull emailTextFieldBorderColor;
@property (nonatomic, strong) UIColor * _Nonnull emailTextFieldColor;
@property (nonatomic) BOOL isErrorImageRequired;
@property (nonatomic, strong) UIFont * _Nonnull emailTextFieldFontStyle;
@property (nonatomic, copy) NSString * _Nonnull emailTextFieldAccessibilityLabel;
@property (nonatomic, copy) NSString * _Nonnull emptyEmailAddressErrorMessage;
@property (nonatomic, copy) NSString * _Nonnull invalidEmailAddressErrorMessage;
@property (nonatomic, strong) UIColor * _Nonnull errorMessageTextColor;
@property (nonatomic, copy) NSString * _Nonnull emailHintText;
@property (nonatomic, copy) NSData * _Nullable emailErrorImage;
@property (nonatomic, strong) UIFont * _Nonnull emailErrorFontStyle;
@property (nonatomic) NSInteger emailErrorImageHeight;
@property (nonatomic) NSInteger emailErrorImageWidth;
@property (nonatomic) NSInteger errorFieldBottomSpacing;
@property (nonatomic) NSInteger errorFieldBottomSpacingAtLandscape;
@property (nonatomic) NSInteger emailViewCornerRadius;
@property (nonatomic) NSInteger emailViewBorderWidth;
@property (nonatomic, strong) UIColor * _Nonnull emailViewBorderColor;
@property (nonatomic, copy) NSString * _Nonnull mailSentFailureErrorMessage;
@property (nonatomic, copy) NSString * _Nullable emailSpecID;
@property (nonatomic) NSInteger emailFieldMaxChars;
@end

@class NSNumber;

SWIFT_CLASS("_TtC17NuanceMessagingUI16EngageParameters")
@interface EngageParameters : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSString * _Nullable siteID;
@property (nonatomic, copy) NSString * _Nullable agentGroupID;
@property (nonatomic, copy) NSString * _Nullable businessUnitID;
@property (nonatomic, copy) NSString * _Nullable businessRuleID;
@property (nonatomic, copy) NSString * _Nullable initialMessage;
@property (nonatomic, copy) NSString * _Nullable openerText;
@property (nonatomic, copy) NSString * _Nullable brName;
@property (nonatomic, strong) NSNumber * _Nullable autoID;
@property (nonatomic, strong) NSNumber * _Nullable pageID;
@property (nonatomic, strong) NSNumber * _Nullable priority;
@property (nonatomic, strong) NSNumber * _Nullable qmSpecID;
@property (nonatomic, strong) NSNumber * _Nullable qt;
@property (nonatomic, copy) NSString * _Nullable scriptID;
@property (nonatomic) BOOL isAsyncEngagement;
@property (nonatomic, copy) NSString * _Nonnull asyncMode;
@property (nonatomic, copy) NSString * _Nullable asyncDays;
@property (nonatomic, copy) NSString * _Nullable customerName;
@property (nonatomic, copy) NSString * _Nullable agentOutcome;
@property (nonatomic, copy) NSString * _Nullable automatonDataPass;
@property (nonatomic, copy) NSString * _Nullable automatonDataMap;
@property (nonatomic, copy) NSString * _Nullable brAttributes;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable dataPass;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nullable agentAttributes;
@property (nonatomic) NSInteger agentAssistedCount;
@property (nonatomic) NSInteger customerAssistedCount;
@property (nonatomic) NSInteger pcs_agent_count;
@property (nonatomic) NSInteger pcs_customer_count;
@property (nonatomic, strong) NSNumber * _Nullable openerID;
@property (nonatomic, copy) NSString * _Nullable openerName;
@property (nonatomic, copy) NSString * _Nullable callType;
@property (nonatomic, copy) NSString * _Nullable closeOnEnd;
@property (nonatomic, copy) NSString * _Nullable host;
@property (nonatomic, copy) NSString * _Nullable authKeyId;
@property (nonatomic, copy) NSString * _Nullable emailSpecID;
@end

@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC17NuanceMessagingUI24FileUploadViewController")
@interface FileUploadViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface FileUploadViewController (SWIFT_EXTENSION(NuanceMessagingUI)) <UINavigationControllerDelegate>
@end

@class UIImagePickerController;

@interface FileUploadViewController (SWIFT_EXTENSION(NuanceMessagingUI)) <UIImagePickerControllerDelegate>
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
@end

@class UIDocumentPickerViewController;
@class NSURL;

@interface FileUploadViewController (SWIFT_EXTENSION(NuanceMessagingUI)) <UIDocumentPickerDelegate>
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)controller didPickDocumentsAtURLs:(NSArray<NSURL *> * _Nonnull)urls;
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)controller didPickDocumentAtURL:(NSURL * _Nonnull)url;
@end


SWIFT_CLASS("_TtC17NuanceMessagingUI24FileUploadViewProperties")
@interface FileUploadViewProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) UIColor * _Nonnull selectFileButtonBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull selectPhotoButtonBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull closeButtonBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull selectFileButtonTitleColor;
@property (nonatomic, strong) UIColor * _Nonnull selectPhotoButtonTitleColor;
@property (nonatomic, strong) UIColor * _Nonnull closeButtonTitleColor;
@property (nonatomic, strong) UIColor * _Nonnull selectFileButtonBorderColor;
@property (nonatomic, strong) UIColor * _Nonnull selectPhotoButtonBorderColor;
@property (nonatomic, strong) UIColor * _Nonnull closeButtonBorderColor;
@property (nonatomic) CGFloat selectFileButtonBorderWidth;
@property (nonatomic) CGFloat selectPhotoButtonBorderWidth;
@property (nonatomic) CGFloat closeButtonBorderWidth;
@property (nonatomic) CGFloat selectFileButtonCornerRadius;
@property (nonatomic) CGFloat selectPhotoButtonCornerRadius;
@property (nonatomic) CGFloat closeButtonCornerRadius;
@property (nonatomic, strong) UIColor * _Nonnull normalMessageTextColor;
@property (nonatomic, strong) UIColor * _Nonnull errorMessageTextColor;
@property (nonatomic, copy) NSString * _Nonnull fileUploadDisclaimerText;
@property (nonatomic, copy) NSString * _Nonnull fileUploadSelectFileButtonTitle;
@property (nonatomic, copy) NSString * _Nonnull fileUploadSelectPhotoButtonTitle;
@property (nonatomic, copy) NSString * _Nonnull fileUplaodCloseButtonTitle;
@property (nonatomic, copy) NSString * _Nonnull fileTypeNotAllowedErrorMessage;
@property (nonatomic, copy) NSString * _Nonnull fileTooLargeErrorMessage;
@property (nonatomic, copy) NSString * _Nonnull fileUploadFailureErrorMessage;
@property (nonatomic, copy) NSString * _Nonnull fileUploadRetryMessage;
@property (nonatomic, copy) NSString * _Nonnull fileUploadSuccessMessage;
@property (nonatomic, copy) NSString * _Nonnull fileUploadRetryButtonTitle;
@property (nonatomic, copy) NSString * _Nonnull fileUploadCancelRetryButtonTitle;
@end


SWIFT_CLASS("_TtC17NuanceMessagingUI26FooterSeparationProperties")
@interface FooterSeparationProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) BOOL isSeperationFooterRequired;
@property (nonatomic) NSInteger height;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColor;
@end

typedef SWIFT_ENUM(NSInteger, LinkButtonPosition, open) {
  LinkButtonPositionLeft = 0,
  LinkButtonPositionCenter = 1,
  LinkButtonPositionRight = 2,
};


SWIFT_CLASS("_TtC17NuanceMessagingUI21LoadingViewController")
@interface LoadingViewController : UIViewController
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17NuanceMessagingUI21LoadingViewProperties")
@interface LoadingViewProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) BOOL showPreviousMessageLoading;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic) float backgroundColorOpacity;
@property (nonatomic, copy) NSString * _Nonnull loadingMessage;
@property (nonatomic, strong) UIColor * _Nonnull loadingMessageColor;
@property (nonatomic) BOOL displayTextInBold;
@property (nonatomic) BOOL displayTextInItalic;
@property (nonatomic, strong) UIFont * _Nonnull messageFontStyle;
@end

typedef SWIFT_ENUM(NSInteger, MessagingErrorStates, open) {
  MessagingErrorStatesNETWORK_ERROR = 0,
  MessagingErrorStatesAGENT_LEFT = 1,
  MessagingErrorStatesSERVICE_NOT_AVAILABLE = 2,
  MessagingErrorStatesSERVICE_DENIED = 3,
  MessagingErrorStatesTIMEOUT = 4,
  MessagingErrorStatesAGENT_MSG_FAILED = 5,
  MessagingErrorStatesAGENT_LOST = 6,
  MessagingErrorStatesNONE = 7,
};


SWIFT_CLASS("_TtC17NuanceMessagingUI23MessagingViewProperties")
@interface MessagingViewProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) BOOL showOpenerOnConversationResolved;
@property (nonatomic) BOOL isAllignToBulletPoints;
@property (nonatomic) BOOL enableDVV;
@property (nonatomic, copy) NSString * _Nonnull openerLoadingMessage;
@property (nonatomic, strong) UIColor * _Nonnull openerLoadingMessageTxtColor;
@property (nonatomic) BOOL centerAlignCustomMessageImage;
@property (nonatomic) BOOL showCustomMessageImage;
@property (nonatomic) NSInteger messageInfoImageWidth;
@property (nonatomic) NSInteger messageInfoImageHeight;
@property (nonatomic) enum UIScrollViewKeyboardDismissMode keyboardDismissMode;
@property (nonatomic) UIModalPresentationStyle viewControllerPresentationStyle;
@property (nonatomic) BOOL hugCustomerMessageContent;
@property (nonatomic) BOOL hugAgentMessageContent;
@property (nonatomic, strong) UIFont * _Nonnull newMessageAlertFontStyle;
@property (nonatomic, copy) NSString * _Nonnull newMessageAlertText;
@property (nonatomic, strong) UIColor * _Nonnull newMessageAlertBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull newMessageAlertTextColor;
@property (nonatomic) NSInteger newMessageAlertBottomMargin;
@property (nonatomic) NSInteger newMessageAlertLeftMargin;
@property (nonatomic) NSInteger newMessageAlertRightMargin;
@property (nonatomic) NSInteger newMessageAlertHeight;
@property (nonatomic) NSInteger newMessageAlertBorderWidth;
@property (nonatomic) NSInteger newMessageAlertCornerRadius;
@property (nonatomic, strong) UIColor * _Nonnull newMessageAlertBorderColor;
@property (nonatomic) BOOL isNinaWebRequired;
@property (nonatomic) NSInteger setSpaceBetweenBubble;
@property (nonatomic) BOOL isChatFromBottom;
@property (nonatomic) NSInteger bottomChatBottomPadding;
@property (nonatomic) double delayRenderingVAResponse;
@property (nonatomic, strong) ChatToCallPropertieClass * _Nullable chatToCallSwitcherProperties;
@property (nonatomic, strong) UIColor * _Nonnull messagingTranscriptBackgorundColor;
@property (nonatomic, copy) NSData * _Nullable agentIconImageData;
@property (nonatomic, copy) NSString * _Nonnull defaultOpenerMessage;
@property (nonatomic) BOOL isAgentIconRequired;
@property (nonatomic) BOOL showNameInBubbles;
@property (nonatomic) BOOL showNameInTimeStamp;
@property (nonatomic, strong) UIColor * _Nonnull agentNameTextColor;
@property (nonatomic, strong) UIColor * _Nonnull customerNameTextColor;
@property (nonatomic, strong) UIColor * _Nonnull agentMessageBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull agentMessageTextColor;
@property (nonatomic, strong) UIColor * _Nonnull agentMessageBorderColor;
@property (nonatomic) NSInteger agentMessageCornerRadius;
@property (nonatomic) NSInteger agentMessageBorderWidth;
@property (nonatomic, strong) UIFont * _Nonnull agentMessageFontStyle;
@property (nonatomic) NSInteger agentTopPadding;
@property (nonatomic) NSInteger agentBottomPadding;
@property (nonatomic) NSInteger agentLeftPadding;
@property (nonatomic) NSInteger agentRightPadding;
@property (nonatomic) NSTextAlignment agentMessageTextAlignment;
@property (nonatomic) NSInteger agentMessageLeftMargin;
@property (nonatomic) NSInteger agentMessageRightMargin;
@property (nonatomic, copy) NSData * _Nullable agentSpeechIcon;
@property (nonatomic, copy) NSData * _Nullable ninaSpeechIcon;
@property (nonatomic, strong) UIColor * _Nonnull customerMessageBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull customerMessageTextColor;
@property (nonatomic, strong) UIColor * _Nonnull customerMessageBorderColor;
@property (nonatomic) NSInteger customerMessageCornerRadius;
@property (nonatomic) NSInteger customerMessageBorderWidth;
@property (nonatomic, strong) UIFont * _Nonnull customerMessageFontStyle;
@property (nonatomic) NSInteger customerTopPadding;
@property (nonatomic) NSInteger customerBottomPadding;
@property (nonatomic) NSInteger customerLeftPadding;
@property (nonatomic) NSInteger customerRightPadding;
@property (nonatomic) NSInteger customerMessageLeftMargin;
@property (nonatomic) NSInteger customerMessageRightMargin;
@property (nonatomic, copy) NSData * _Nullable customerSpeechIcon;
@property (nonatomic) NSTextAlignment customerMessageTextAlignment;
@property (nonatomic, strong) UIColor * _Nonnull systemMessageTextColor;
@property (nonatomic, strong) UIColor * _Nonnull agentTypingTextColor;
@property (nonatomic, strong) UIFont * _Nonnull agentTypingFontStyle;
@property (nonatomic, strong) UIFont * _Nonnull systemMessageFontStyle;
@property (nonatomic, strong) UIFont * _Nonnull customerNameFontStyle;
@property (nonatomic, strong) UIFont * _Nonnull agentNameFontStyle;
@property (nonatomic) NSInteger footerViewHeight;
@property (nonatomic, strong) UIColor * _Nonnull systemMessageBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull systemMessageBorderColor;
@property (nonatomic) NSInteger systemMessageCornerRadius;
@property (nonatomic) NSInteger systemMessageBorderWidth;
@property (nonatomic) NSTextAlignment systemMessageAllignment;
@property (nonatomic) NSInteger systemMessageTopPadding;
@property (nonatomic) NSInteger systemMessageBottomPadding;
@property (nonatomic) NSInteger systemMessageLeftPadding;
@property (nonatomic) NSInteger systemMessageRightPadding;
@property (nonatomic) BOOL persistTransferStartMessage;
@property (nonatomic) BOOL persistTransferConnectedMessage;
@property (nonatomic, strong) UIColor * _Nonnull agentTypingMessageBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull agentTypingMessageBorderColor;
@property (nonatomic) NSInteger agentTypingMessageCornerRadius;
@property (nonatomic) NSInteger agentTypingMessageBorderWidth;
@property (nonatomic) NSTextAlignment agentTypingMessageAllignment;
@property (nonatomic) NSInteger agentTypingMessageTopPadding;
@property (nonatomic) NSInteger agentTypingMessageBottomPadding;
@property (nonatomic) NSInteger agentTypingMessageLeftPadding;
@property (nonatomic) NSInteger agentTypingMessageRightPadding;
@property (nonatomic, copy) NSString * _Nonnull agentTypingAccessibilityMessage;
@property (nonatomic) BOOL showTypingAnimation;
@property (nonatomic) BOOL hideStoppedTyping;
@property (nonatomic, strong) UIImage * _Nullable typingStaticImage;
@property (nonatomic) NSInteger typingStaticImageWidth;
@property (nonatomic) NSInteger typingStaticImageHeight;
@property (nonatomic) NSInteger typingStaticImageLeftMargin;
@property (nonatomic) NSInteger typingStaticImageTopMargin;
@property (nonatomic, strong) UIColor * _Nonnull typingStaticImageBackgroundColor;
@property (nonatomic, strong) UIImage * _Nullable typingAnimationImage;
@property (nonatomic) NSInteger typingAnimationImageWidth;
@property (nonatomic) NSInteger typingAnimationImageHeight;
@property (nonatomic) NSInteger typingAnimationImageLeftMargin;
@property (nonatomic) NSInteger typingAnimationImageTopMargin;
@property (nonatomic, strong) UIColor * _Nonnull typingAnimationImageBackgroundColor;
@property (nonatomic) NSInteger infoMessageLeftMargin;
@property (nonatomic) NSInteger infoMessageTopMargin;
@property (nonatomic) NSInteger infoMessageRightMargin;
@property (nonatomic, copy) NSData * _Nullable agentBackgroundImageData;
@property (nonatomic, copy) NSData * _Nullable customerBackgroundImageData;
@property (nonatomic) BOOL setConversationBackgroundImage;
@property (nonatomic) enum UITableViewRowAnimation bubbleAnimationStyle;
@property (nonatomic) BOOL setSpeachBubbleView;
@property (nonatomic) BOOL setInLineBubbleView;
@property (nonatomic) NSInteger setAgentBackgroundImageStreachTopInset;
@property (nonatomic) NSInteger setAgentBackgroundImageStreachLeftInset;
@property (nonatomic) NSInteger setAgentBackgroundImageStreachRightInset;
@property (nonatomic) NSInteger setAgentBackgroundImageStreachBottomInset;
@property (nonatomic) NSInteger setCustomerBackgroundImageStreachTopInset;
@property (nonatomic) NSInteger setCustomerBackgroundImageStreachLeftInset;
@property (nonatomic) NSInteger setCustomerBackgroundImageStreachRightInset;
@property (nonatomic) NSInteger setCustomerBackgroundImageStreachBottomInset;
@property (nonatomic) BOOL setMessageTimeStamp;
@property (nonatomic, copy) NSString * _Nonnull setMessageTimeStampFormat;
@property (nonatomic, strong) UIColor * _Nonnull agentTimeStampBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull agentTimeStampTextColor;
@property (nonatomic, strong) UIColor * _Nonnull agentTimeStampBorderColor;
@property (nonatomic) NSInteger agentTimeStampCornerRadius;
@property (nonatomic) NSInteger agentTimeStampBorderWidth;
@property (nonatomic, strong) UIFont * _Nonnull agentTimeStampFontStyle;
@property (nonatomic) NSTextAlignment agentTimeStampTextAllignment;
@property (nonatomic) NSInteger agentTimeStampLeftPadding;
@property (nonatomic) NSInteger agentTimeStampRightPadding;
@property (nonatomic) NSInteger agentTimeStampTopPadding;
@property (nonatomic) NSInteger agentTimeStampBottomPadding;
@property (nonatomic) NSInteger agentTimeStampLeftMargin;
@property (nonatomic) NSInteger agentTimeStampRightMargin;
@property (nonatomic) NSInteger agentTimeStampTopMargin;
@property (nonatomic) NSInteger agentTimeStampBottomMargin;
@property (nonatomic, strong) UIColor * _Nonnull customerTimeStampBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull customerTimeStampTextColor;
@property (nonatomic, strong) UIColor * _Nonnull customerTimeStampBorderColor;
@property (nonatomic) NSInteger customerTimeStampCornerRadius;
@property (nonatomic) NSInteger customerTimeStampBorderWidth;
@property (nonatomic, strong) UIFont * _Nonnull customerTimeStampFontStyle;
@property (nonatomic) NSTextAlignment customerTimeStampTextAllignment;
@property (nonatomic) NSInteger customerTimeStampLeftPadding;
@property (nonatomic) NSInteger customerTimeStampRightPadding;
@property (nonatomic) NSInteger customerTimeStampTopPadding;
@property (nonatomic) NSInteger customerTimeStampBottomPadding;
@property (nonatomic) NSInteger customerTimeStampLeftMargin;
@property (nonatomic) NSInteger customerTimeStampRightMargin;
@property (nonatomic) NSInteger customerTimeStampTopMargin;
@property (nonatomic) NSInteger customerTimeStampBottomMargin;
@property (nonatomic) NSInteger setAgentIconImagePosition;
@property (nonatomic) NSInteger setCustomerIconImagePosition;
@property (nonatomic, strong) UIColor * _Nonnull htmlLinkColor;
@property (nonatomic, strong) UIColor * _Nonnull htmlLinkGreyScaleModeColor;
@property (nonatomic) float linkStrokeWidth;
@property (nonatomic, strong) UIFont * _Nullable htmlLinkButtonFont;
@property (nonatomic) BOOL isAgentShowUrlLookup;
@property (nonatomic) BOOL isCustomerShowUrlLookup;
@property (nonatomic, strong) UIColor * _Nonnull urlContentTitleTextColor;
@property (nonatomic, strong) UIColor * _Nonnull urlContentDetailTextColor;
@property (nonatomic, strong) UIFont * _Nonnull urlContentTitleFont;
@property (nonatomic, strong) UIFont * _Nonnull urlContentDetailFont;
@property (nonatomic) NSInteger urlContentBackgroundMaxHeight;
@property (nonatomic, strong) UIColor * _Nonnull urlContentBackgroundViewColor;
@property (nonatomic) NSInteger urlContentBackgroundViewLeftMargin;
@property (nonatomic) NSInteger urlContentBackgroundViewRightMargin;
@property (nonatomic) NSInteger urlContentBackgroundViewTopMargin;
@property (nonatomic) NSInteger urlContentImageLeftPandding;
@property (nonatomic) NSInteger urlContentImageTopPandding;
@property (nonatomic) NSInteger urlContentImageBottomPandding;
@property (nonatomic) NSInteger urlContentImageWidth;
@property (nonatomic) NSInteger urlContentTitleTopPadding;
@property (nonatomic) NSInteger urlContentTitleLeftPadding;
@property (nonatomic) NSInteger urlContentTitleRightPadding;
@property (nonatomic) NSInteger urlContentTitleHeight;
@property (nonatomic) NSInteger urlContentDetailLeftPadding;
@property (nonatomic) NSInteger urlContentDetailRightPadding;
@property (nonatomic) NSInteger urlContentDetailTopPadding;
@property (nonatomic) NSInteger urlContentDetailBottomPadding;
@property (nonatomic) BOOL showSurveyDialog;
@property (nonatomic) BOOL enablePCSCiv2;
@property (nonatomic, copy) NSURL * _Nullable htmlFileUrlPathForTranscript;
@property (nonatomic) BOOL displayNinaLinksAsButtons;
@property (nonatomic, strong) UIColor * _Nonnull linkButtonBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull linkButtonTextColor;
@property (nonatomic) NSInteger linkButtonCornerRadius;
@property (nonatomic) NSInteger linkButtonWidth;
@property (nonatomic, strong) UIColor * _Nonnull linkButtonBorderColor;
@property (nonatomic) NSInteger linkButtonBorderWidth;
@property (nonatomic, copy) NSData * _Nullable linkButtonBackgroundImage;
@property (nonatomic) NSTextAlignment linkButtonTextAllignment;
@property (nonatomic) CGFloat linkButtonLeftPadding;
@property (nonatomic) CGFloat linkButtonRightPadding;
@property (nonatomic, copy) NSString * _Nonnull agentTypingMessage;
@property (nonatomic, copy) NSString * _Nonnull agentStoppedTypingMessage;
@property (nonatomic) BOOL ignoreDefaultChime;
@property (nonatomic) BOOL playVoiceOverOnRestore;
@property (nonatomic) BOOL showFirstImageOut;
@property (nonatomic) NSInteger vaImageBorderWidth;
@property (nonatomic) NSInteger vaImageCornerRadius;
@property (nonatomic) NSInteger vaImageLeftMargin;
@property (nonatomic) NSInteger vaImageRigthMargin;
@property (nonatomic, strong) UIColor * _Nonnull vaImageBorderColor;
@property (nonatomic, strong) UIColor * _Nonnull vaImageBackgroundColor;
@property (nonatomic) NSInteger vaImageheight;
@property (nonatomic) enum UIViewContentMode vaImageMode;
@property (nonatomic, strong) UIColor * _Nonnull inlineBackgroundColor;
@property (nonatomic) NSInteger inlineImageheight;
@property (nonatomic) NSInteger inlineImagewidth;
@property (nonatomic) enum UIViewContentMode inlineImageMode;
@property (nonatomic) BOOL showAsyncHeader;
@property (nonatomic) BOOL showAsyncAgentExit;
@property (nonatomic) BOOL showAsyncAgentResoved;
@property (nonatomic, strong) UIColor * _Nonnull asyncHeaderBorderColor;
@property (nonatomic, strong) UIColor * _Nonnull asyncHeaderBackgroundColor;
@property (nonatomic) NSInteger asyncHeaderBorderWidth;
@property (nonatomic) NSInteger asyncHeaderCornerRadius;
@property (nonatomic) NSInteger asyncHeaderLeftMargin;
@property (nonatomic) NSInteger asyncHeaderRigthMargin;
@property (nonatomic) NSInteger asyncHeaderTopMargin;
@property (nonatomic) NSInteger asyncHeaderBottomMargin;
@property (nonatomic) NSInteger asyncHeaderHeight;
@property (nonatomic, strong) UIFont * _Nonnull asyncHeaderTextFontStyle;
@property (nonatomic, copy) NSString * _Nonnull asyncHeaderText;
@property (nonatomic) BOOL groupMsgs;
@property (nonatomic) NSInteger spaceBetweenGroupingCells;
@property (nonatomic) BOOL displayTransferStatusMessages;
@property (nonatomic) BOOL displayQueuedMessagesInAsync;
@property (nonatomic) BOOL showAvatarForRichWidget;
@property (nonatomic) BOOL resetMsgCounterVAExit;
@property (nonatomic) BOOL showActivityIndicator;
@property (nonatomic) BOOL delegateDeeplink;
@property (nonatomic) BOOL showOpenerTextInAsync;
@property (nonatomic) BOOL sendResolveCommand;
@end

@class NSMutableArray;

SWIFT_CLASS("_TtC17NuanceMessagingUI19NinaCobraProperties")
@interface NinaCobraProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) BOOL isAsrTTSRequired;
@property (nonatomic) BOOL showNinaAnimInCenter;
@property (nonatomic) NSInteger ninaAnimCenterHolderHeight;
@property (nonatomic, strong) UIColor * _Nonnull ninaAnimCenterHolderColor;
@property (nonatomic, strong) UIColor * _Nonnull ninaCenterViewBackgroundColor;
@property (nonatomic) BOOL enableContinousListening;
@property (nonatomic) BOOL playTTSOnRestore;
@property (nonatomic) BOOL playTTSOnlyOnASRInput;
@property (nonatomic) BOOL playOpener;
@property (nonatomic, strong) NSData * _Nullable successChimeSoundData;
@property (nonatomic, strong) NSData * _Nullable startListeningSoundData;
@property (nonatomic, strong) NSData * _Nullable errorChimeSoundData;
@property (nonatomic, strong) NSData * _Nullable connectionSuccessChimeSoundData;
@property (nonatomic, strong) NSData * _Nullable connectionFailedChimeSoundData;
@property (nonatomic, copy) NSString * _Nonnull ninaProcessingErrorText;
@property (nonatomic, strong) UIColor * _Nonnull ninaProcessingViewBackgroundColor;
@property (nonatomic) NSInteger ninaProcessingViewLeftMargin;
@property (nonatomic) NSInteger ninaProcessingViewRightMargin;
@property (nonatomic) NSInteger ninaProcessingViewTopMargin;
@property (nonatomic) NSInteger ninaProcessingViewBottomMargin;
@property (nonatomic, copy) NSString * _Nonnull ninaProcessingText;
@property (nonatomic, strong) UIColor * _Nonnull ninaProcessingTextColor;
@property (nonatomic, strong) UIColor * _Nonnull ninaProcessingTextBackgroundColor;
@property (nonatomic, strong) UIFont * _Nonnull ninaProcessingTextFontStyle;
@property (nonatomic) NSTextAlignment ninaProcessingTextAllignment;
@property (nonatomic) NSInteger ninaProcessingTextLeftMargin;
@property (nonatomic) NSInteger ninaProcessingTextRightMargin;
@property (nonatomic) NSInteger ninaProcessingTextTopMargin;
@property (nonatomic) NSInteger ninaProcessingTextBottomMargin;
@property (nonatomic, copy) NSString * _Nonnull ninaNoInternetText;
@property (nonatomic, strong) UIColor * _Nonnull ninaOverlayTextColor;
@property (nonatomic, strong) UIColor * _Nonnull ninaOverlayBackgroundColor;
@property (nonatomic) float ninaOverlayOpacity;
@property (nonatomic, strong) UIFont * _Nonnull ninaOverlayFontStyle;
@property (nonatomic, strong) UIImage * _Nullable ninaNoInternetImage;
@property (nonatomic, strong) UIImage * _Nullable ninaSleepingAnimationImage;
@property (nonatomic, strong) UIImage * _Nullable ninaProcessingAnimationImage;
@property (nonatomic, strong) UIImage * _Nullable ninaListeningAnimationImage;
@property (nonatomic, strong) UIImage * _Nullable ninaAlertAnimationImage;
@property (nonatomic, strong) UIImage * _Nullable ninaSucessAnimationImage;
@property (nonatomic, strong) NSMutableArray * _Nullable ninaRecordingEnergyPromptImages;
@property (nonatomic, strong) UIImage * _Nullable ninaIdleStaticImage;
@property (nonatomic, strong) UIImage * _Nullable ninaAnimCenterBackgroundImage;
@property (nonatomic) BOOL ninaWakeupWordRequired;
@property (nonatomic, copy) NSString * _Nonnull ninaWakeupWordAcmodFilename;
@property (nonatomic, copy) NSString * _Nonnull ninaWakeupWordClcFilename;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable ninaWakeupWordArray;
@end

@class GetMessageResponse;

SWIFT_PROTOCOL("_TtP17NuanceMessagingUI23NuanceMessagingDelegate_")
@protocol NuanceMessagingDelegate
@optional
- (void)onMinimized;
- (void)onNinaExternalLinkWithUrlLinkMessage:(NSString * _Nonnull)urlLinkMessage;
- (void)onClosed;
- (void)onErrorWithState:(enum MessagingErrorStates)state;
- (void)onDisplayed;
- (void)onCustomerMessageWithIsVA:(BOOL)isVA;
- (void)onAgentAssignedWithName:(NSString * _Nonnull)name;
- (void)interceptVAMessageWithSuccesResp:(GetMessageResponse * _Nullable)succesResp;
- (void)onVAMessageWithMessage:(NSDictionary * _Nonnull)message;
- (void)onTitleOption1;
- (void)onTitleOption2;
- (void)onEngagementCreated;
- (void)onEngagementEnded;
- (void)onConversationResolved;
- (void)onNewMessageWithMessage:(GetMessageResponse * _Nullable)message;
@end

@class TitleBarProperties;
@class SendButtonProperties;
@class WebViewSettings;
@class NinaSetting;
@class NinaServerConfiguration;
@class RichContentProperties;
@class WKWebView;

SWIFT_CLASS("_TtC17NuanceMessagingUI29NuanceMessagingViewController")
@interface NuanceMessagingViewController : UINavigationController
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(BOOL)animated;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)setTranscriptViewPropetiesWithProperties:(MessagingViewProperties * _Nonnull)properties;
- (void)setFooterSeparationViewPropetiesWithProperties:(FooterSeparationProperties * _Nonnull)properties;
- (void)setCustomerInputPropertiesWithProperties:(CustomerInputFieldProperties * _Nonnull)properties;
- (void)setTitleBarPropertiesWithProperties:(TitleBarProperties * _Nonnull)properties;
- (void)setSendButtonPropertiesWithProperties:(SendButtonProperties * _Nonnull)properties;
- (void)setStringPropertiesWithProperties:(CustomerInformationMessages * _Nonnull)properties;
- (void)setEmailViewPropertiesWithProperties:(EmailViewProperties * _Nonnull)properties;
- (void)setLoadingViewPropertiesWithProperties:(LoadingViewProperties * _Nonnull)properties;
- (void)setWebViewSettingsWithProperties:(WebViewSettings * _Nonnull)properties;
- (void)setNinaActionSoundPropertiesWithProperties:(NinaCobraProperties * _Nonnull)properties;
- (void)setNinaSettingPropertiesWithProperties:(NinaSetting * _Nonnull)properties;
- (void)setNinaServerConfigurationPropertiesWithProperties:(NinaServerConfiguration * _Nonnull)properties;
- (void)setMessagingDelegateWithDelegate:(id _Nonnull)delegate;
- (void)setRichContentPropertiesWithProperties:(RichContentProperties * _Nonnull)properties;
- (void)setFileUploadViewPropertiesWithProperties:(FileUploadViewProperties * _Nonnull)properties;
- (void)setViewPropertiesWithProperties:(LoadingViewProperties * _Nonnull)properties;
- (void)setHtmlTextWithTxt:(NSString * _Nonnull)txt;
- (void)setChatHeaderPropertiesWithProperties:(ChatHeaderProperties * _Nonnull)properties;
- (NuanceMessagingViewController * _Nonnull)launchMessagingViewControllerWithParams:(EngageParameters * _Nonnull)params forAudioCall:(BOOL)forAudioCall SWIFT_WARN_UNUSED_RESULT;
- (NuanceMessagingViewController * _Nonnull)restoreMessagingViewControllerWithWebview:(WKWebView * _Nullable)webview forAudioCall:(BOOL)forAudioCall SWIFT_WARN_UNUSED_RESULT;
- (void)minimizeMessaging;
- (void)closeAndDismiss;
- (void)updateMessagingTitleWithTitle:(NSString * _Nonnull)title;
- (void)updateMessagingLogoWithData:(NSData * _Nonnull)data;
- (void)updateMessagingTitleAndLogoWithTitle:(NSString * _Nonnull)title data:(NSData * _Nonnull)data;
- (void)displayAgentTypingWithMsg:(NSString * _Nonnull)msg;
- (void)addMessageToChatWindowWithMsg:(NSString * _Nonnull)msg;
- (void)addSystemToChatWindowWithMsg:(NSString * _Nonnull)msg;
- (void)clearSystemFromChatWindow;
- (void)addCustomVAMsgWithMsg:(NSString * _Nonnull)msg name:(NSString * _Nonnull)name;
- (void)toggleKeyboardVisiblityWithShow:(BOOL)show;
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=5.0);
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC17NuanceMessagingUI22ProgressViewProperties")
@interface ProgressViewProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) BOOL displayProgressText;
@property (nonatomic) BOOL displayMessageText;
@property (nonatomic, strong) UIFont * _Nonnull messageTextFont;
@property (nonatomic, strong) UIFont * _Nonnull progressTextFont;
@property (nonatomic, strong) UIColor * _Nonnull messageTextColor;
@property (nonatomic, strong) UIColor * _Nonnull progressTextColor;
@property (nonatomic, copy) NSString * _Nonnull messageText;
@property (nonatomic, copy) NSString * _Nonnull progressTextFormat;
@property (nonatomic, strong) UIColor * _Nonnull progressTintColor;
@property (nonatomic, strong) UIColor * _Nonnull trackTintColor;
@property (nonatomic) CGFloat progressViewHeight;
@property (nonatomic) CGFloat progressViewWidth;
@end


SWIFT_CLASS("_TtC17NuanceMessagingUI21RichContentProperties")
@interface RichContentProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) UIColor * _Nonnull formWidgetBackgroundColor;
@property (nonatomic) NSInteger formWidgetTypeLeftMargin;
@property (nonatomic) NSInteger formWidgetTypeRightMargin;
@property (nonatomic) NSInteger formWidgetTypePadding;
@property (nonatomic) NSInteger formWidgetTypeTopMargin;
@property (nonatomic) NSInteger formWidgetTypeBottomMargin;
@property (nonatomic, strong) UIColor * _Nonnull receiptWidgetBackgroundColor;
@property (nonatomic) NSInteger receiptWidgetTypeLeftMargin;
@property (nonatomic) NSInteger receiptWidgetTypeRightMargin;
@property (nonatomic) NSInteger receiptWidgetTypeTopMargin;
@property (nonatomic) NSInteger receiptWidgetTypeBottomMargin;
@property (nonatomic, strong) UIColor * _Nonnull cardWidgetBackgroundColor;
@property (nonatomic) NSInteger cardWidgetTypeLeftMargin;
@property (nonatomic) NSInteger cardWidgetTypeRightMargin;
@property (nonatomic) NSInteger cardWidgetTypePadding;
@property (nonatomic) NSInteger cardWidgetTypeTopMargin;
@property (nonatomic) NSInteger cardWidgetTypeBottomMargin;
@property (nonatomic, strong) UIColor * _Nonnull quickreplyWidgetBackgroundColor;
@property (nonatomic) NSInteger quickreplyWidgetTypeLeftMargin;
@property (nonatomic) NSInteger quickreplyWidgetTypeRightMargin;
@property (nonatomic) NSInteger quickreplyWidgetTypePadding;
@property (nonatomic) NSInteger quickreplyWidgetTypeTopMargin;
@property (nonatomic) NSInteger quickreplyWidgetTypeBottomMargin;
@property (nonatomic, strong) UIColor * _Nonnull caroselWidgetBackgroundColor;
@property (nonatomic) NSInteger caroselWidgetTypeLeftMargin;
@property (nonatomic) NSInteger caroselWidgetTypeRightMargin;
@property (nonatomic) NSInteger caroselWidgetTypePadding;
@property (nonatomic) NSInteger caroselWidgetTypeTopMargin;
@property (nonatomic) NSInteger caroselWidgetTypeBottomMargin;
@property (nonatomic, copy) NSString * _Nonnull jsonStirng;
@property (nonatomic, copy) NSString * _Nonnull jsonStyleStirng;
@end


SWIFT_CLASS("_TtC17NuanceMessagingUI20SendButtonProperties")
@interface SendButtonProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSData * _Nullable buttonImageData;
@property (nonatomic, copy) NSData * _Nullable disableImageData;
@property (nonatomic, strong) UIColor * _Nonnull borderColor;
@property (nonatomic) NSInteger borderWidth;
@property (nonatomic) NSInteger cornerRadius;
@property (nonatomic, copy) NSString * _Nonnull buttonTitle;
@property (nonatomic, strong) UIColor * _Nonnull backgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull textColor;
@property (nonatomic, copy) NSArray<UIColor *> * _Nonnull gradientEffect;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull gradientEffectLocations;
@property (nonatomic) BOOL useGradientEffect;
@property (nonatomic) NSInteger buttonFieldRightMargin;
@property (nonatomic) NSInteger buttonFieldTopMargin;
@property (nonatomic) NSInteger buttonFieldBottomMargin;
@property (nonatomic) NSInteger buttonWidth;
@property (nonatomic) NSInteger buttonHeight;
@property (nonatomic) BOOL toggleSendStateAfterMsgSend;
@property (nonatomic, strong) UIColor * _Nonnull disableBorderColor;
@property (nonatomic) NSInteger disableBorderWidth;
@property (nonatomic) NSInteger disableCornerRadius;
@property (nonatomic, copy) NSString * _Nonnull disableButtonTitle;
@property (nonatomic, strong) UIColor * _Nonnull disableBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull disableTextColor;
@property (nonatomic, copy) NSArray<UIColor *> * _Nonnull disableGradientEffect;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull disableGradientEffectLocations;
@property (nonatomic) BOOL disableUseGradientEffect;
@end

typedef SWIFT_ENUM(NSInteger, TitleBarElement, open) {
  TitleBarElementClose = 0,
  TitleBarElementMinimize = 1,
  TitleBarElementEmail = 2,
  TitleBarElementShare = 3,
  TitleBarElementChime = 4,
  TitleBarElementLogoImage = 5,
  TitleBarElementOption1 = 6,
  TitleBarElementOption2 = 7,
};


SWIFT_CLASS("_TtC17NuanceMessagingUI18TitleBarProperties")
@interface TitleBarProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic) BOOL statusBarColorLight;
@property (nonatomic, copy) NSString * _Nonnull messagingBarTitle;
@property (nonatomic, strong) UIColor * _Nonnull messagingBarBackgroundColor;
@property (nonatomic, strong) UIColor * _Nonnull messagingBarTitleColor;
@property (nonatomic, strong) UIFont * _Nonnull messagingTitleFontStyle;
@property (nonatomic) BOOL isMessagingTitleBold;
@property (nonatomic, strong) UIColor * _Nonnull shareButtonTextColor;
@property (nonatomic, copy) NSData * _Nullable shareImageData;
@property (nonatomic, copy) NSString * _Nonnull shareTextName;
@property (nonatomic) NSInteger shareButtonWidth;
@property (nonatomic) NSInteger shareButtonHeight;
@property (nonatomic, strong) UIColor * _Nonnull option1ButtonTextColor;
@property (nonatomic, copy) NSData * _Nullable option1ImageData;
@property (nonatomic, copy) NSString * _Nonnull option1TextName;
@property (nonatomic) NSInteger option1ButtonWidth;
@property (nonatomic) NSInteger option1ButtonHeight;
@property (nonatomic, strong) UIColor * _Nonnull option2ButtonTextColor;
@property (nonatomic, copy) NSData * _Nullable option2ImageData;
@property (nonatomic, copy) NSString * _Nonnull option2TextName;
@property (nonatomic) NSInteger option2ButtonWidth;
@property (nonatomic) NSInteger option2ButtonHeight;
@property (nonatomic, strong) UIColor * _Nonnull chimeButtonTextColor;
@property (nonatomic, copy) NSData * _Nullable chimeOnImageData;
@property (nonatomic, copy) NSData * _Nullable chimeOffImageData;
@property (nonatomic, copy) NSString * _Nonnull chimeTextName;
@property (nonatomic, copy) NSString * _Nonnull chimeTextOn;
@property (nonatomic, copy) NSString * _Nonnull chimeTextOff;
@property (nonatomic) NSInteger chimeButtonWidth;
@property (nonatomic) NSInteger chimeButtonHeight;
@property (nonatomic, strong) NSData * _Nullable chimeSoundData;
@property (nonatomic, strong) UIColor * _Nonnull emailButtonTextColor;
@property (nonatomic, copy) NSData * _Nullable emailImageData;
@property (nonatomic, copy) NSString * _Nonnull emailTextName;
@property (nonatomic) NSInteger emailButtonWidth;
@property (nonatomic) NSInteger emailButtonHeight;
@property (nonatomic, strong) UIColor * _Nonnull closeButtonTextColor;
@property (nonatomic, copy) NSData * _Nullable closeImageData;
@property (nonatomic, copy) NSString * _Nonnull closeTextName;
@property (nonatomic) NSInteger closeButtonWidth;
@property (nonatomic) NSInteger closeButtonHeight;
@property (nonatomic, strong) UIColor * _Nonnull minimizeButtonTextColor;
@property (nonatomic, copy) NSData * _Nullable minimizeImageData;
@property (nonatomic, copy) NSString * _Nonnull minimizeTextName;
@property (nonatomic) NSInteger minimizeButtonWidth;
@property (nonatomic) NSInteger minimizeButtonHeight;
@property (nonatomic) NSInteger minimumSpaceBetweenTitleButton;
@property (nonatomic) BOOL showShareButton;
@property (nonatomic) BOOL showLogo;
@property (nonatomic, copy) NSData * _Nullable logoImageData;
@property (nonatomic) NSInteger logoImageWidth;
@property (nonatomic) NSInteger logoImageHeight;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull leftTitleBarIcons;
@property (nonatomic, copy) NSArray<NSNumber *> * _Nonnull rightTitleBarIcons;
@property (nonatomic) enum TitlePosition setTitlePosition;
@property (nonatomic) BOOL isTitleLogoTogetherRequired;
@property (nonatomic, copy) NSData * _Nullable titleImageData;
@property (nonatomic) NSInteger titleImageWidth;
@property (nonatomic) NSInteger titleImageHeight;
@end

typedef SWIFT_ENUM(NSInteger, TitlePosition, open) {
  TitlePositionLeft = 0,
  TitlePositionCenter = 1,
};







@interface UINavigationController (SWIFT_EXTENSION(NuanceMessagingUI))
@property (nonatomic, readonly, strong) UIViewController * _Nullable childViewControllerForStatusBarStyle;
@end




SWIFT_CLASS("_TtC17NuanceMessagingUI15WebViewSettings")
@interface WebViewSettings : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable WVdomains;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
